### ISSUE TITLE
Wrong version of HtmlAgilityPack for Sitecore 9.3

### ISSUE THREAD

**Issue by rkeitel** [Kasaku/Sitecore.Sweep#2]
By clicking "Save" in the content editor the following error occurs:

> Could not load file or assembly 'HtmlAgilityPack, Version=1.4.6.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Sitecore 9.3 uses version 1.4.9.5 instead of 1.4.6.0.

**Comment by rkeitel** [comment]
Sorry for this issue. With assembly binding entry it is solved.

**Comment by AlexKasaku** [comment]
No problem @rkeitel!
